# =====================================================
# SERVER
# =====================================================
server.port=8080

# =====================================================
# APPLICATION
# =====================================================
spring.application.name=MAEPIM

# =====================================================
# POSTGRESQL
# =====================================================
#spring.datasource.url=jdbc:postgresql://localhost:5432/maepim
spring.datasource.url=jdbc:postgresql://ep-falling-voice-azcu89e4-pooler.c-3.ap-southeast-1.aws.neon.tech/MAEPIM?user=neondb_owner&password=npg_uzA1GN8ZRODk&sslmode=require&channelBinding=require
#spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_uzA1GN8ZRODk}

spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================================
# JPA
# =====================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.default_schema=maepim
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Bangkok

# =====================================================
# FLYWAY
# =====================================================
spring.flyway.enabled=true
spring.flyway.schemas=maepim
spring.flyway.default-schema=maepim
spring.flyway.locations=classpath:db/migration

# =====================================================
# JWT
# =====================================================
maepim.app.jwtSecret=${JWT_SECRET:sKw9taq8grVQEv5vbxL0t/V4vkv+ndfCdAxUvFoum5MPixBN1922zAL5v8Zk+Vwlckh2xWWnAsYrjugJ5CbfYA==}
maepim.app.jwtExpirationMs=900000
maepim.app.jwtRefreshExpirationMs=604800000
maepim.app.otpExpirationMs=300000

# =====================================================
# MAIL
# =====================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maepim.noreply@gmail.com
spring.mail.password=bgkh abea nvad zace
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =====================================================
# LOGGING
# =====================================================
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE